export const strings = {
  en: {
    'nav.dashboard': 'Dashboard',
    'nav.resources': 'My Resources',
    'nav.projects': 'Projects',
    'nav.scheduling': 'Scheduling Board',
    'nav.documents': 'Documents & Compliance',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.transport': 'Transport & Logistics',
    'nav.financial': 'Financial Overview',
    'common.loading': 'Loading…',
    'common.project': 'Project',
    'common.unassigned': 'Unassigned',
    'common.day': 'day',
    'auth.login': 'Log In',
    'auth.logout': 'Log Out',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loginError': 'Invalid email or password',
    'mobile.checkIn': 'Check-In',
    'mobile.equipmentStatus': 'Equipment Status',
    'widget.liveWorkerMap': 'Live Worker Map',
    'widget.offSiteAlert': '{{count}} possibly off-site',
    'widget.onSiteNow': 'On Site Now',
    'widget.mapPinCount': '{{count}} worker pins',
    'mobile.startSharing': 'Start Location Sharing',
    'mobile.stopSharing': 'Stop Location Sharing',
    'mobile.reportWorkerLocation': 'Report Worker Location',
    'transport.requestTransport': 'Request Transport',
    'transport.activeTransports': 'Active Transports',
    'transport.inTransit': 'In Transit',
    'transport.delayed': 'Delayed',
    'transport.mapPlaceholder': 'Live transport map',
    'transport.yard': 'Yard',
    'transport.fleetPool': 'Transport Fleet',
    'transport.dropVehicleHint': 'Drop a vehicle here to assign',
    'transport.urgent': 'URGENT',
    'transport.noDriverAvailable': 'No driver available to assign',
    'transport.status.pending': 'Pending',
    'transport.status.assigned': 'Assigned',
    'transport.status.in_transit': 'In Transit',
    'transport.status.delivered': 'Delivered',
    'financial.todaySpend': "Today's Spend",
    'financial.monthToDate': 'This Month',
    'financial.idleAssetsCosting': 'Idle Assets Costing',
    'financial.budgetOf': 'Budget: SAR {{amount}}',
    'financial.costPerProjectChart': 'Cost per project chart',
    'financial.delayAlerts': 'Delay Cost Alerts',
    'financial.noDelays': 'No delay costs logged recently',
    'financial.estimatedLoss': 'Estimated loss: SAR {{amount}}',
    'financial.mtdProjectCosts': 'Month-to-Date Project Costs',
    'financial.budget': 'Budget',
    'financial.actual': 'Actual',
  },
  ar: {
    'nav.dashboard': 'لوحة التحكم',
    'nav.resources': 'مواردي',
    'nav.projects': 'المشاريع',
    'nav.scheduling': 'لوحة الجدولة',
    'nav.documents': 'الوثائق والامتثال',
    'nav.reports': 'التقارير',
    'nav.settings': 'الإعدادات',
    'nav.transport': 'النقل واللوجستيات',
    'nav.financial': 'النظرة المالية',
    'common.loading': 'جارٍ التحميل…',
    'common.project': 'المشروع',
    'common.unassigned': 'غير مُخصص',
    'common.day': 'يوم',
    'auth.login': 'تسجيل الدخول',
    'auth.logout': 'تسجيل الخروج',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.loginError': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'mobile.checkIn': 'تسجيل الحضور',
    'mobile.equipmentStatus': 'حالة المعدات',
    'widget.liveWorkerMap': 'خريطة العمال المباشرة',
    'widget.offSiteAlert': '{{count}} ربما خارج الموقع',
    'widget.onSiteNow': 'في الموقع الآن',
    'widget.mapPinCount': '{{count}} علامات عمال',
    'mobile.startSharing': 'بدء مشاركة الموقع',
    'mobile.stopSharing': 'إيقاف مشاركة الموقع',
    'mobile.reportWorkerLocation': 'الإبلاغ عن موقع العامل',
    'transport.requestTransport': 'طلب نقل',
    'transport.activeTransports': 'عمليات النقل النشطة',
    'transport.inTransit': 'قيد النقل',
    'transport.delayed': 'متأخر',
    'transport.mapPlaceholder': 'خريطة النقل المباشرة',
    'transport.yard': 'الساحة',
    'transport.fleetPool': 'أسطول النقل',
    'transport.dropVehicleHint': 'اسحب مركبة هنا للتخصيص',
    'transport.urgent': 'عاجل',
    'transport.noDriverAvailable': 'لا يوجد سائق متاح للتخصيص',
    'transport.status.pending': 'قيد الانتظار',
    'transport.status.assigned': 'تم التخصيص',
    'transport.status.in_transit': 'قيد النقل',
    'transport.status.delivered': 'تم التسليم',
    'financial.todaySpend': 'إنفاق اليوم',
    'financial.monthToDate': 'هذا الشهر',
    'financial.idleAssetsCosting': 'تكلفة الأصول الخاملة',
    'financial.budgetOf': 'الميزانية: {{amount}} ريال',
    'financial.costPerProjectChart': 'رسم تكلفة كل مشروع',
    'financial.delayAlerts': 'تنبيهات تكلفة التأخير',
    'financial.noDelays': 'لا توجد تكاليف تأخير مسجلة مؤخرًا',
    'financial.estimatedLoss': 'الخسارة المقدرة: {{amount}} ريال',
    'financial.mtdProjectCosts': 'تكاليف المشاريع من بداية الشهر',
    'financial.budget': 'الميزانية',
    'financial.actual': 'الفعلي',
  },
};
